language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t amitbiderman/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true amitbiderman/docker-react npm run test